# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://https://github.com/Lzpgithub/Lzpgithub.github.io
date_format: "ordinal"
title: Aris
subtitle: "海阔凭鱼跃   天高任鸟飞"
description: "欢迎来到Aris个人博客"
keywords: Aris, Lzpgithub
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/Lzpgithub/Lzpgithub.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: ZiPeng Lu
organization: Sogou, Inc.
organization_url: https://www.sogou.com
location: LiaoNing, China 卢子鹏
email: 1317343152@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 目录分类

  -
    href: /wiki/
    label: 在线编程

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: Lzpgithub
douban_username: freedim
facebook_username: Luzipeng
weibo_username: Aris

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: Lzpgithub
disqus_username: Lzpgithub

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Win32 SDK,QT,MFC]
popular_repos: ['chinese-copywriting-guidelines','android-reverse-engineering', 'csdncommenter', 'Lzpgithub.github.io', 'vim-markdown-toc']
contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']
